apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service-api
spec:
  selector:
    matchLabels:
      app: category-service-api
  replicas: 1
  template:
    metadata:
      labels:
        app: category-service-api
    spec:
      containers:
        - name: category-service-api
          image: vouckerplatform/category-service:fb905687001e01adb9488dcef46ba9274801f424
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: category-service-api
spec:
  selector:
    app: category-service-api
  ports:
    - protocol: TCP
      port: 4000
  type: LoadBalancer
