apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service-api
spec:
  selector:
    matchLabels:
      app: category-service-api
  replicas: 1
  template:
    metadata:
      labels:
        app: category-service-api
    spec:
      containers:
        - name: category-service-api
          image: vouckerplatform/category-service
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          env:
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_MQ_URI
                  optional: false
            - name: RABBIT_MQ_CATEGORY_QUEUE
              value: 'CATEGORY'
            - name: PORT
              value: '3000'
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AUTH0_AUDIENCE
                  optional: false
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AUTH0_DOMAIN
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_USER
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_PASSWORD
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_PORT
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_HOST
                  optional: false
            - name: DATABASE_NAME
              value: category_db
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: category-service-api-svc
spec:
  selector:
    app: category-service-api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
