apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - inventory-service-deployment.yaml
  - ingress.yaml
  - category-service-deployment.yaml
  - location-service-deployment.yaml
  - order-service-deployment.yaml
  - rabbitmq-deployment.yaml
  - secret.yaml
  - store-service-deployment.yaml
  - voucher-service-deployment.yaml
