apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-api
spec:
  selector:
    matchLabels:
      app: order-service-api
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service-api
    spec:
      containers:
        - name: order-service-api
          image: vouckerplatform/order-service
          env:
            - name: RABBIT_MQ_URI
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: RABBIT_MQ_URI
                  optional: false
            - name: RABBIT_MQ_ORDER_QUEUE
              value: 'ORDER'
            - name: RABBIT_MQ_INVENTORY_QUEUE
              value: 'INVENTORY'
            - name: PORT
              value: '3000'
            - name: AUTH0_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AUTH0_AUDIENCE
                  optional: false
            - name: AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: AUTH0_DOMAIN
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_USER
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_PASSWORD
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_PORT
                  optional: false
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DATABASE_HOST
                  optional: false
            - name: DATABASE_NAME
              value: order_db
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-api-svc
spec:
  selector:
    app: order-service-api
  ports:
    - protocol: TCP
      port: 3000
  type: ClusterIP
