version: '3.9'
services:
  voucher_service:
    platform: linux/amd64
    container_name: voucher_service
    build:
      context: .
      dockerfile: ./apps/voucher/Dockerfile
      target: production
    env_file:
      - ./apps/voucher/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4000:3000'
  store_service:
    platform: linux/amd64
    container_name: store_service
    build:
      context: .
      dockerfile: ./apps/store/Dockerfile
      target: production
    env_file:
      - ./apps/store/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4001:3000'
  location_service:
    platform: linux/amd64
    container_name: location_service
    build:
      context: .
      dockerfile: ./apps/location/Dockerfile
      target: production
    env_file:
      - ./apps/location/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4005:3000'
  category_service:
    platform: linux/amd64
    container_name: category_service
    build:
      context: .
      dockerfile: ./apps/category/Dockerfile
      target: production
    env_file:
      - ./apps/category/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4004:3000'
  order_service:
    platform: linux/amd64
    container_name: order_service
    build:
      context: .
      dockerfile: ./apps/order/Dockerfile
      target: production
    env_file:
      - ./apps/order/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4002:3000'
  inventory_service:
    platform: linux/amd64  
    container_name: inventory_service
    build:
      context: .
      dockerfile: ./apps/inventory/Dockerfile
      target: production
    env_file:
      - ./apps/inventory/.env
    depends_on:
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4003:3000'

  nginx_load_balancer:
    container_name: loader_balancer
    image: nginx
    restart: always
    volumes:
      - ./nginx/unbuntu/default.conf:/etc/nginx/nginx.conf
    ports:
      - '80:80'
  rabbitmq:
    container_name: event_bus
    image: rabbitmq
    restart: always
    ports:
      - '5672:5672'
