
name: FE CI/CD
on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './FE'
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './FE/package-lock.json'
      - name: Install dependencies
        run: npm i
      - name: Run Build
        run: npm run build 
