name: Category Service CI/CD - gcp
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  PROJECT_ID: ${{secrets.GKE_PROJECT}}
#  GAR_LOCATION: europe
  GKE_CLUSTER: autopilot-cluster-voucker-platform
  GKE_ZONE: europe-west1
  DEPLOYMENT_NAME: github_action_automation_deployment_category_service_api
  IMAGE: category-service-api
  # TAG: 0.0.1

jobs:

  setup-build-publish-deploy:
    name: Set up Build Publish Deploy
    runs-on: ubuntu-latest
    environment: production
    
    permissions: 
      contents: 'read'
      id-token: 'write'
    
    defaults:
      run:
        working-directory: './BE'
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - name: Configure Docker
        run: |-
          gcloud --quiet auth configure-docker
 
      - name: GKE 
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
            cluster_name: ${{ env.GKE_CLUSTER }}
            location: ${{ env.GKE_ZONE }}
            credentials: ${{ secrets.GKE_SA_KEY }}      

           
      
#       - name: Set up GKE credentials
#         uses: google-github-actions/get-gke-credentials@v0
#         with:
#           cluster_name: ${{ env.GKE_CLUSTER }}
#           location: ${{ env.GKE_ZONE }}      
#           project_id: voucher
      



#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v3
#         with:
#           node-version: ${{ matrix.node-version }}
#           cache: 'npm'
#           cache-dependency-path: './BE/package-lock.json'

#       - name: Install dependencies
#         run: npm ci

#       - name: Run Build
#         run: npm run build category --if-present

#       - name: Setup Google Cloud CLI
#         uses: google-github-actions/auth@v0
#         with:
#          credentials_json: '${{ secrets.GKE_SA_KEY }}'

#       - name: Set up QEMU
#         uses: docker/setup-qemu-action@v2
#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2

#       - name: Docker configuration
#         run: |-
#           echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

#       - name: Set up GKE credentials
#         uses: google-github-actions/get-gke-credentials@v0
#         with:
#           cluster_name: ${{ env.GKE_CLUSTER }}
#           location: ${{ env.GKE_ZONE }}
    
    
    
    
    
#       - name: Build Docker image
#         run: |-
#           docker build \
#             --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
#             --build-arg GITHUB_SHA="$GITHUB_SHA" \
#             --build-arg GITHUB_REF="$GITHUB_REF" \
          
#       - name: Publish
#         run: |-
#           docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"
          
          
  

     
