name: Node.js CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './BE'
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: './BE/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run Build
        run: npm run build voucker --if-present
      - name: Login to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME  }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build/Push image        
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: vouckerplatform/voucher-service:${{github.sha}}
